#!/bin/bash

NAME=PHP
BASE_REPO=php
VARIANTS=(browsers node node-browsers)

TAG_FILTER="grep -v -e rc -e beta"

IMAGE_CUSTOMIZATIONS=$(cat <<'EOF'

RUN echo 'Defaults    env_keep += "PHP_INI_DIR"' >> /etc/sudoers.d/env_keep

# Install composer
RUN php -r "copy('https://raw.githubusercontent.com/composer/getcomposer.org/master/web/installer', 'composer-setup.php');" && \
    php composer-setup.php && \
    php -r "unlink('composer-setup.php');" && \
    mv composer.phar /usr/local/bin/composer

# Install libraries
RUN apt install -y libicu-dev zlib1g-dev libzip-dev libpng-dev libxml2-dev libxslt-dev libfreetype6-dev libjpeg-dev

# Install intl with specific ICU version
RUN apt install -y autoconf file g++ gcc libc-dev make pkg-config re2c
RUN curl -Ls http://download.icu-project.org/files/icu4c/52.1/icu4c-52_1-src.tgz > /tmp/icu4c-src.tgz \
    && cd /tmp && tar xzf icu4c-src.tgz && cd /tmp/icu/source && ./configure && make && make install \
    && rm -rf /tmp/icu /tmp/icu4c-src.tgz \
    && docker-php-ext-configure intl && docker-php-ext-install intl

# Install gd
RUN docker-php-ext-configure gd --enable-gd-native-ttf --with-freetype-dir=/usr/include/freetype2 --with-png-dir=/usr/include --with-jpeg-dir=/usr/include \
    && docker-php-ext-install gd

# Install PHP extensions required by Magento
RUN docker-php-ext-install bcmath pdo_mysql soap xsl zip

# Increase PHP memory limit
RUN echo 'memory_limit = 2G' >> /usr/local/etc/php/conf.d/docker-php-memory-limit.ini

# Install grunt
RUN npm install -g grunt-cli

EOF
)

source ../shared/images/generate-node.sh
source ../shared/images/generate.sh
